artifact_location: file:///Volumes/Development/Development/assignment/MLOps_ASS1/mlruns_local/940153133682441300
creation_time: 1754450037543
experiment_id: '940153133682441300'
last_update_time: 1754450037543
lifecycle_stage: active
name: prediction_logging
