# Prometheus configuration
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "flask-app"
    static_configs:
      - targets: ["app:5000"]
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]
