# Prometheus configuration for California Housing API Monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'housing-api'
    static_configs:
      - targets: ['housing-api:5001']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  - job_name: 'housing-api-custom'
    static_configs:
      - targets: ['housing-api:5001']
    metrics_path: '/api/monitoring/metrics'
    scrape_interval: 30s
    scrape_timeout: 15s

  - job_name: "docker"
    static_configs:
      - targets: ["localhost:9323"]
