artifact_location: file:///Volumes/Development/Development/assignment/MLOps_ASS1/mlruns_local/403593752715199070
creation_time: 1754450033131
experiment_id: '403593752715199070'
last_update_time: 1754450033131
lifecycle_stage: active
name: simple_local_test
