artifact_location: file:///Volumes/Development/Development/assignment/MLOps_ASS1/mlruns_local/579547869513438310
creation_time: 1754450037608
experiment_id: '579547869513438310'
last_update_time: 1754450037608
lifecycle_stage: active
name: api_predictions
