# API Configuration
api:
  host: "0.0.0.0"
  port: 5001
  debug: false
  
# Model Configuration
model:
  path: "models/model.pkl"
  
# Monitoring
monitoring:
  metrics_enabled: true
  prometheus_port: 8000
  
# Logging
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
# Health Check
health:
  enabled: true
  endpoint: "/health"
  
# CORS Settings
cors:
  enabled: true
  origins: ["*"]
