# Model Configuration
model:
  type: "decision_tree"
  random_state: 42
  test_size: 0.2
  
  # Decision Tree Parameters
  decision_tree:
    max_depth: 10
    min_samples_split: 5
    min_samples_leaf: 2
    
  # Linear Regression Parameters  
  linear_regression:
    fit_intercept: true
    
# Data Configuration
data:
  input_file: "data/housing.csv"
  target_column: "median_house_value"
  
# MLflow Configuration
mlflow:
  experiment_name: "california_housing_experiment"
  tracking_uri: "http://localhost:5000"
  
# Feature Engineering
features:
  categorical:
    - ocean_proximity
  numerical:
    - longitude
    - latitude
    - housing_median_age
    - total_rooms
    - total_bedrooms
    - population
    - households
    - median_income
