data_path: data/housing.csv
output_dir: reports
models_dir: models
run_eda: true
run_feature_engineering: true
run_model_training: true

# Feature Engineering Configuration
feature_engineering:
  include_transformations: true
  include_scaling: true
  include_polynomial: false
  target_column: median_house_value

# Model Training Configuration  
model_training:
  test_size: 0.2
  random_state: 42
  models:
    - linear_regression
    - decision_tree
    - random_forest
  mlflow_experiment_name: "housing_price_prediction"
  
# EDA Configuration
eda:
  save_plots: true
  plot_format: png
  correlation_threshold: 0.7
  skewness_threshold: 1.0

# Logging Configuration
logging:
  level: INFO
  log_file: logs/pipeline.log
  console_output: true
