channels:
- conda-forge
dependencies:
- python=3.11.11
- pip<=25.2
- pip:
  - mlflow==2.16.2
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - psutil==5.9.0
  - scikit-learn==1.5.1
  - scipy==1.16.1
name: mlflow-env
